[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
